### PR TITLE
Use rio accessor for geospatial information

### PR DESCRIPTION
**Pull request by mdpiper**
This PR updates *bmi-topography* to use the *rioxarray* [rio accessor](https://corteva.github.io/rioxarray/stable/rioxarray.html#rioxarray-rio-accessors) for geopspatial information.

### CODE REVIEW

**Comment by mdpiper** [comment]
@mcflugen What would you think about allowing BMI grid spacing to have negative values? Currently, grid spacing is the distance (so a positive value) between the nodes of a grid along a coordinate axis. The issue is geospatial imagery usually treats the top left corner as the origin. A negative *y*-value for the grid spacing would indicate the grid is built from this origin in the negative *y* direction.

**Comment by mcflugen** [comment]
> @mcflugen What would you think about allowing BMI grid spacing to have negative values?

I think we've done this before, actually. I'm not sure, however, if *pymt* supports it or if the *bmi-tester* is ok with it (but I think I am ok with it).

**Comment by mdpiper** [comment]
> I think we've done this before, actually. I'm not sure, however, if _pymt_ supports it or if the _bmi-tester_ is ok with it (but I think I am ok with it).

The *bmi-tester* doesn't like it. Would it be OK if I submitted a PR to change this?

**Comment by mdpiper** [comment]
Until #49 is resolved, I'm disabling testing on Windows with python=3.10.

**Pull request merged**
