### PR TITLE
Provide a better reason for 401 errors

### PR DESCRIPTION
**Pull request by mcflugen**
This pull request tries to address #40 but keeping track where a user's API key came from (i.e. was it supplied as a keyword, through an environment variable, through a file, or a demo key).

### CODE REVIEW

**Comment by mcflugen** [comment]
If this seems like a good idea, I'll tidy up the existing unit tests and add some new ones.

**Comment by mdpiper** [comment]
This looks great, thank you! I especially appreciate that it will resolve #40.

**Comment by mcflugen** [comment]
I added a new module, *errors.py*, to hold *bmi-topography*-specific exceptions. In the future we may want to add additional exceptions that the *Topography* class could raise instead of the generic *ValueError*.

I still want to add some documentation before this is merged.

The new modules now have 100% coverage. 🎉

**Comment by mcflugen** [comment]
@mdpiper Ok, now I'm done. Please have a look and let me know what you think.

**Review by mdpiper — APPROVED** [review]

**Comment by mdpiper** [comment]
@mcflugen OK if I merge this? I'd then like to make a release. Would you prefer incrementing from 0.7 to 0.7.1 or 0.8?

**Comment by mcflugen** [comment]
@mdpiper Merge away!

If this is basically the only new addition, I would say 0.7.1.

**Pull request merged**
